name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: npm install

    # 4. Construir la imagen Docker
    - name: Build Docker Image
      run: docker build -t node-js-sample .

    # 5. Probar la aplicación
    - name: Test Docker Container
      run: |
        docker run -d -p 3000:3000 --name test-container node-js-sample
        sleep 5
        curl -f http://localhost:3000 || exit 1
        docker stop test-container && docker rm test-container

    # 6. Publicar la imagen en Docker Hub (si las pruebas son exitosas)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker tag node-js-sample ${{ secrets.DOCKERHUB_USERNAME }}/node-js-sample:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-js-sample:latest
